#!/usr/bin/env npx ts-node
import { createGenerator, Config } from 'ts-json-schema-generator';
import * as fs from 'fs';
import * as path from 'path';

const config: Config = {
  path: path.resolve(__dirname, '../src/bridge/bridge-types.ts'),
  tsconfig: path.resolve(__dirname, '../tsconfig.json'),
  type: '*',
  skipTypeCheck: true,
};

const outputDir = path.resolve(__dirname, '../src/bridge/schemas');

// Types to generate schemas for
const types = [
  // Request bodies
  'StartBody',
  'DocumentOpenBody',
  'DocumentChangeBody',
  'DocumentCloseBody',
  'PositionBody',
  'ReferencesBody',
  'SymbolsBody',
  // Responses
  'ErrorResponse',
  'SuccessResponse',
  'StartResponse',
  'StatusResponse',
  'CompletionResponse',
  'HoverResponse',
  'DefinitionResponse',
  'ReferencesResponse',
  'SymbolsResponse',
  'DiagnosticsResponse',
];

// Ensure output directory exists
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

const generator = createGenerator(config);
const schemas: Record<string, unknown> = {};

for (const typeName of types) {
  try {
    const schema = generator.createSchema(typeName);
    schemas[typeName] = schema;
    console.log(`Generated schema for ${typeName}`);
  } catch (err) {
    console.error(`Failed to generate schema for ${typeName}:`, err);
  }
}

// Write combined schemas file
const outputPath = path.join(outputDir, 'index.ts');
const content = `// Auto-generated by scripts/generate-schemas.ts
// Do not edit manually

export const schemas = ${JSON.stringify(schemas, null, 2)} as const;
`;

fs.writeFileSync(outputPath, content);
console.log(`\nSchemas written to ${outputPath}`);
