#!/usr/bin/env npx tsx
import { createGenerator, Config } from 'ts-json-schema-generator';
import * as fs from 'fs';
import * as path from 'path';

const config: Config = {
  path: path.resolve(__dirname, '../src/bridge/bridge-types.ts'),
  tsconfig: path.resolve(__dirname, '../tsconfig.json'),
  type: '*',
  skipTypeCheck: true,
};

const outputDir = path.resolve(__dirname, '../src/bridge/schemas');

// Types to generate schemas for
const types = [
  // Request bodies
  'StartBody',
  'DocumentOpenBody',
  'DocumentChangeBody',
  'DocumentCloseBody',
  'PositionBody',
  'ReferencesBody',
  'SymbolsBody',
  // Responses
  'ErrorResponse',
  'SuccessResponse',
];

// Ensure output directory exists
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

const generator = createGenerator(config);

// Collect all schemas and their definitions
const allDefinitions: Record<string, unknown> = {};

for (const typeName of types) {
  try {
    const schema = generator.createSchema(typeName) as {
      definitions?: Record<string, unknown>;
      $ref?: string;
    };

    // Extract definitions and add to global definitions
    if (schema.definitions) {
      for (const [defName, defSchema] of Object.entries(schema.definitions)) {
        allDefinitions[defName] = defSchema;
      }
    }

    console.log(`Generated schema for ${typeName}`);
  } catch (err) {
    console.error(`Failed to generate schema for ${typeName}:`, err);
  }
}

// Convert #/definitions/ references to Fastify format (SchemaName#)
function convertRefsToFastify(obj: unknown): unknown {
  if (obj === null || obj === undefined) return obj;

  if (typeof obj === 'string') {
    // Convert #/definitions/TypeName to TypeName#
    return obj.replace(/#\/definitions\/([^/]+)/g, '$1#');
  }

  if (Array.isArray(obj)) {
    return obj.map(convertRefsToFastify);
  }

  if (typeof obj === 'object') {
    const result: Record<string, unknown> = {};
    for (const [key, value] of Object.entries(obj as Record<string, unknown>)) {
      result[key] = convertRefsToFastify(value);
    }
    return result;
  }

  return obj;
}

// Convert all definitions to Fastify format
const convertedDefinitions = convertRefsToFastify(allDefinitions) as Record<string, unknown>;

// Write combined schemas file
const outputPath = path.join(outputDir, 'index.ts');
const content = `// Auto-generated by scripts/generate-schemas.ts
// Do not edit manually

// All schema definitions with Fastify-compatible $ref format
export const schemaDefinitions = ${JSON.stringify(convertedDefinitions, null, 2)} as const;
`;

fs.writeFileSync(outputPath, content);
console.log(`\nSchemas written to ${outputPath}`);
